### ISSUE TITLE
objects not exported by some bioconductor packages

### ISSUE THREAD

**Issue by tolot27** [gschofl/biofiles#2]
After building the package with RStudio I get the following error:

```
installing to Z:/Documents/R/win-library/biofiles/libs/x64
** R
** inst
** preparing package for lazy loading
Error : object 'unlist' is not exported by 'namespace:Biostrings'
ERROR: lazy loading failed for package 'biofiles'
```

Checking the NAMESPACE file for the recently installed Biostrings packages reveals that `unlist` is exported but as a method. Testing the package (`devtools::test()`) produces three additional warnings:

```
Warnmeldungen:
1: object 'unlist' is not exported by 'namespace:Biostrings' 
2: object 'queryHits' is not exported by 'namespace:IRanges' 
3: object 'split' is not exported by 'namespace:IRanges' 
4: object 'subjectHits' is not exported by 'namespace:IRanges'
```

I'm using R 3.3.0 64 bit and Bioconductor 3.3 with Biostrings 2.40.2. How to solve this problem?

PS: Installing boost_regex was a nightmare.

**Comment by tolot27** [comment]
Okay, got it solved and will provide a PR soon.

**Comment by AbhijitBadve** [comment]
Can you shade light on how you solved the issue? I am having the trouble getting this work as well. I am using R-3.1.1 64-bit and Bioconductor 3.0. 
Thanks.
Abhijit

**Comment by gschofl** [comment]
I have cleaned up the code so that it works with the current Bioconductor 3.3 release. This might not be backwards compatible with older Bioconductor packages, though, as they have moved a lot of stuff from IRanges and Biostrings over to S4Vectors and XVectors over the last few releases. Could you confirm if it works for you now, or if not, what breaks?

**Comment by AbhijitBadve** [comment]
Thanks! The problem is indeed with incompatible versions of bioconductor.  It resolved after I updated all repos mentioned in your comment along with bioconductor itself.
